listeners:
  - name: OSResources
    type: timed
    interval: 600 # Interval in ticks

storages:
  - name: WebSocket
    type: websocket
    url: ws://localhost:8080/ws
  - name: PostgreSQLConsumer
    type: database
    url: jdbc:postgresql://localhost:5432/minecraft
    username: user
    password: pass
  - name: Csv
    type: file
    path: data/stats.json
  